#!/bin/bash

FILE_NAME_WITH_EXTENSION="$1"

LANGUAGE_NAME="mojo"
COMMAND_CHECK_LANGUAGE_VERSION="mojo --version"
COMMAND_RUN_LANGUAGE_CODE="mojo \"$FILE_NAME_WITH_EXTENSION\""

bash ./runner/runner.sh \
    "$LANGUAGE_NAME" \
    "$COMMAND_CHECK_LANGUAGE_VERSION" \
    "$COMMAND_RUN_LANGUAGE_CODE"