#!/bin/bash

FILE_NAME_WITH_EXTENSION="$1"

LANGUAGE_NAME="r"
COMMAND_CHECK_LANGUAGE_VERSION="R --version"
COMMAND_RUN_LANGUAGE_CODE="Rscript \"$FILE_NAME_WITH_EXTENSION\""

bash ./runner/runner.sh \
    "$LANGUAGE_NAME" \
    "$COMMAND_CHECK_LANGUAGE_VERSION" \
    "$COMMAND_RUN_LANGUAGE_CODE"