#!/bin/bash

FILE="$1"

LANGUAGE_NAME="go"
COMMAND_CHECK_LANGUAGE_VERSION="go version"
COMMAND_RUN_LANGUAGE_CODE="go run \"$FILE\""

bash ./runner/runner.sh \
    "$LANGUAGE_NAME" \
    "$COMMAND_CHECK_LANGUAGE_VERSION" \
    "$COMMAND_RUN_LANGUAGE_CODE"